project:
  type: website
  output-dir: docs

website:
  title: "R for the Psychology Student"
  page-navigation: true
  description: "Intro to R Course"
  site-url: "https://dr-jt.github.io/r-for-psychology-students/"
  
  sidebar:
    background: "#F2F2F2"
    font-color: "#005098"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Course Prep"
        contents:
          - href: what-is-R.qmd
            text: "What is R?"
          - href: prerequisites.qmd
            text: "Prerequisites"
      - section: "Classes"
        contents:
          - href: classes/class-1.qmd
            text: "Class 1: An Introduction"
          - href: classes/class-2.qmd
            text: "Class 2: Import, Merge, Restructure"
          - href: classes/class-3.qmd
            text: "Class 3: Data Transformation"
          - href: classes/class-4.qmd
            text: "Class 4: Reproducible Projects"
          - href: classes/class-5.qmd
            text: "Class 5: Data Preparation"
          - href: classes/class-6.qmd
            text: "Class 6: Data Scoring"
          - href: classes/class-7.qmd
            text: "Class 7: Quarto Documents"
          - href: classes/class-8.qmd
            text: "Class 8: Data Visualization"
          - href: classes/class-9.qmd
            text: "Class 9: ANOVA"
          - href: classes/class-10.qmd
            text: "Class 10: Regression"
      - section: "Supplemental"
        contents:
          - href: supplemental/r-basics.qmd
            text: "R Basics"
          - href: supplemental/r-intermediate.qmd
            text: "R Intermediate"
          - href: supplemental/tips.qmd
            text: "Useful Tips"
          - href: supplemental/pipe-operator.qmd
            text: "Pipe Operator"
          - href: supplemental/github_copilot.qmd
            text: "GitHub Copilot"
          - href: supplemental/data-prep-qualtrics.qmd
            text: "Data Prep - Qualtrics"
    
format:
  html:
    css: styles.css
    foreground: "#4676a3"
    linkcolor: "#005098"
    theme: 
      light: [cosmo, theme.css]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    df-print: paged
    grid:
      sidebar-width: 315px
    
filters:
  - line-highlight

editor: visual
