project:
  type: website
  output-dir: docs

website:
  title: "R for the Psychology Student"
  page-navigation: true
  description: "Intro to R Course"
  site-url: "https://dr-jt.github.io/r-for-psychology-students/"
  
  sidebar:
    background: "#4676a3"
    font-color: "#ffffff"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Course Information"
        contents:
          - href: what-is-R.qmd
            text: "What is R?"
          - href: prerequisites.qmd
            text: "Prerequisites"
      - section: "Classes"
        contents:
          - href: classes/class-1.qmd
            text: "Class 1"
          - href: classes/class-2.qmd
            text: "Class 2"
          - href: classes/class-3.qmd
            text: "Class 3"
    
format:
  html:
    css: styles.css
    foreground: "#4676a3"
    linkcolor: "#4676a3"
    theme: 
      light: [cosmo, theme.css]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
filters:
  - line-highlight

editor: visual
