project:
  type: website
  output-dir: docs

website:
  title: "R for the Psychology Student"
  page-navigation: true
  description: "Intro to R Course"
  site-url: "https://dr-jt.github.io/r-for-psychology-students/"
  
  sidebar:
    background: "#F2F2F2"
    font-color: "#005098"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Course Prep"
        contents:
          - href: what-is-R.qmd
            text: "What is R?"
          - href: prerequisites.qmd
            text: "Prerequisites"
      - section: "Classes"
        contents:
          - href: classes/class-1.qmd
            text: "Class 1"
          - href: classes/class-2.qmd
            text: "Class 2"
          - href: classes/class-3.qmd
            text: "Class 3"
          - href: classes/class-4.qmd
            text: "Class 4"
          - href: classes/class-5.qmd
            text: "Class 5"
          - href: classes/class-6.qmd
            text: "Class 6"
          - href: classes/class-7.qmd
            text: "Class 7"
          - href: classes/class-8.qmd
            text: "Class 8"
          - href: classes/class-9.qmd
            text: "Class 9"
          - href: classes/class-10.qmd
            text: "Class 10"
      - section: "Supplemental"
        contents:
          - href: supplemental/tips-tricks.qmd
            text: "Tips & Tricks"
          - href: supplemental/github_copilot.qmd
            text: "GitHub Copilot"
          - href: supplemental/data-prep-qualtrics.qmd
            text: "Data Prep - Qualtrics"
    
format:
  html:
    css: styles.css
    foreground: "#4676a3"
    linkcolor: "#005098"
    theme: 
      light: [cosmo, theme.css]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    df-print: paged
    
filters:
  - line-highlight

editor: visual
