---
title: "Class 10"
subtitle: "Statistical Analysis - Regression"
slide-format: revealjs
editor: visual
---

The main objective of this class is to learn how to perfom different types of regression models and generate tables and figures of those models.

## Prepare

-   Install packages for generating regression tables

    -   `sjPlot`, `correlation`, `broom`, `performance`, `parameters`

-   Install packages for regression analyses

    -   `e1071`, `ggeffects`, `mediation`

-   Install packages for path analysis

    -   `lavaan`, `semTools`, `semPlot`

-   Install my packages from GitHub for genearting model tables

    -   First install: `devtools`

    -   Then install packages from GitHub: `modeloutput` and `semoutput`

        ```{r}
        #| eval: false

        install.packages("devtools")

        devtools::install_github("dr-JT/modeloutput")
        devtools::install_github("dr-JT/semoutput")
        ```

## Outline

-   Setup Quarto Document

-   Descriptives

    -   Histograms

-   Correlations

    -   Tables and Scatterplots

-   Regression

    -   Simple Regression

    -   Multiple Regression

    -   Hierarchical Regression

    -   Mediation

    -   Moderation

## Class Materials

📘 [Lecture Content](/lectures/lectures-class-10.html)
